/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarTasksRouteImport } from './../routes/_sidebar/tasks'
import { Route as SidebarOverviewRouteImport } from './../routes/_sidebar/overview'
import { Route as SidebarOntologyRouteImport } from './../routes/_sidebar/ontology'
import { Route as SidebarMeetingsRouteImport } from './../routes/_sidebar/meetings'
import { Route as SidebarConsumptionRouteImport } from './../routes/_sidebar/consumption'
import { Route as SidebarAccountOrgRouteImport } from './../routes/_sidebar/account-org'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarTasksRoute = SidebarTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarOverviewRoute = SidebarOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarOntologyRoute = SidebarOntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarMeetingsRoute = SidebarMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarConsumptionRoute = SidebarConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAccountOrgRoute = SidebarAccountOrgRouteImport.update({
  id: '/account-org',
  path: '/account-org',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-org': typeof SidebarAccountOrgRoute
  '/consumption': typeof SidebarConsumptionRoute
  '/meetings': typeof SidebarMeetingsRoute
  '/ontology': typeof SidebarOntologyRoute
  '/overview': typeof SidebarOverviewRoute
  '/tasks': typeof SidebarTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-org': typeof SidebarAccountOrgRoute
  '/consumption': typeof SidebarConsumptionRoute
  '/meetings': typeof SidebarMeetingsRoute
  '/ontology': typeof SidebarOntologyRoute
  '/overview': typeof SidebarOverviewRoute
  '/tasks': typeof SidebarTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/account-org': typeof SidebarAccountOrgRoute
  '/_sidebar/consumption': typeof SidebarConsumptionRoute
  '/_sidebar/meetings': typeof SidebarMeetingsRoute
  '/_sidebar/ontology': typeof SidebarOntologyRoute
  '/_sidebar/overview': typeof SidebarOverviewRoute
  '/_sidebar/tasks': typeof SidebarTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-org'
    | '/consumption'
    | '/meetings'
    | '/ontology'
    | '/overview'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-org'
    | '/consumption'
    | '/meetings'
    | '/ontology'
    | '/overview'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/account-org'
    | '/_sidebar/consumption'
    | '/_sidebar/meetings'
    | '/_sidebar/ontology'
    | '/_sidebar/overview'
    | '/_sidebar/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/tasks': {
      id: '/_sidebar/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof SidebarTasksRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/overview': {
      id: '/_sidebar/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof SidebarOverviewRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/ontology': {
      id: '/_sidebar/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof SidebarOntologyRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/meetings': {
      id: '/_sidebar/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof SidebarMeetingsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/consumption': {
      id: '/_sidebar/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof SidebarConsumptionRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/account-org': {
      id: '/_sidebar/account-org'
      path: '/account-org'
      fullPath: '/account-org'
      preLoaderRoute: typeof SidebarAccountOrgRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAccountOrgRoute: typeof SidebarAccountOrgRoute
  SidebarConsumptionRoute: typeof SidebarConsumptionRoute
  SidebarMeetingsRoute: typeof SidebarMeetingsRoute
  SidebarOntologyRoute: typeof SidebarOntologyRoute
  SidebarOverviewRoute: typeof SidebarOverviewRoute
  SidebarTasksRoute: typeof SidebarTasksRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAccountOrgRoute: SidebarAccountOrgRoute,
  SidebarConsumptionRoute: SidebarConsumptionRoute,
  SidebarMeetingsRoute: SidebarMeetingsRoute,
  SidebarOntologyRoute: SidebarOntologyRoute,
  SidebarOverviewRoute: SidebarOverviewRoute,
  SidebarTasksRoute: SidebarTasksRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
