/**
 * People / OrgPerson hooks.
 *
 * The deterministic ontology scan endpoint (POST /api/ontology/scan) is
 * called via a typed fetch fallback. The auto-generated client in
 * `@/lib/api` doesn't include this route until the OpenAPI watcher
 * re-runs in the main checkout — once it does, this hook can be migrated
 * to the generated `scanOntology()` client without changing its surface.
 */
import { useMutation, useQueryClient } from "@tanstack/react-query";

export interface ScanPeopleResult {
  calendar_events_visited: number;
  email_threads_visited: number;
  persons_inserted: number;
  persons_updated: number;
  started_at: string;
  finished_at: string;
}

async function postScan(): Promise<ScanPeopleResult> {
  const res = await fetch("/api/ontology/scan", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || `HTTP ${res.status}`);
  }
  return (await res.json()) as ScanPeopleResult;
}

export function useScanPeople() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: postScan,
    onSuccess: () => {
      // Refresh anything that reads from OrgPerson. The list-persons
      // query key is generated by Orval; invalidating by prefix is the
      // simplest way to keep this resilient to client regeneration.
      qc.invalidateQueries({ queryKey: ["listOrgPersons"] });
      qc.invalidateQueries({ queryKey: ["org-persons"] });
    },
  });
}
